name: base
#  moonvision/python-base
#
#  Dependencies include a small set of build-time
#  dependencies to ease compiling libraries.
channels:
  - conda-forge
dependencies:
  - libblas=*=*mkl
  - cffi
  - future
  - mkl=2021.4
  - mkl-include=2021.4
  - ninja
  - numpy=1.21.3
  - python=3.8
  - pyyaml=5.4.1
  - requests
  - setuptools
  - six
  - typing_extensions
  - pip
  - pip:
    - opencv-contrib-python-headless==4.2.0.34
    - opencv-python-headless==4.2.0.34
