name: base
#  moonvision/python-base
#
#  Dependencies include a small set of build-time
#  dependencies to ease compiling libraries.
channels:
  - conda-forge
dependencies:
  # switch all blas requirements to use mkl
  # implementation, see: https://conda-forge.org/docs/maintainer/knowledge_base.html#blas
  # it doesn't constrain the libblas version (1st *), but the build string to end in 'mkl' (2nd *)
  - libblas=*=*mkl
  - cffi
  - future
  - mkl=2023.2.0
  - mkl-include=2023.2.0
  - ninja
  - numpy=1.24.3
  - python=3.8
  - pyyaml=5.4.1
  - requests
  - six
  - typing_extensions
  - pip
  - pip:
    - opencv-contrib-python-headless==4.9.0.80
