name: base
#  moonvision/python-base
#
#  Dependencies include a small set of build-time
#  dependencies to ease compiling libraries.
channels:
  - conda-forge
dependencies:
  # switch all blas requirements to use mkl
  # implementation, see: https://conda-forge.org/docs/maintainer/knowledge_base.html#blas
  # it doesn't constrain the libblas version (1st *), but the build string to end in 'mkl' (2nd *)
  - libblas=*=*mkl
  - cffi>=1.17.0
  - future
  - mkl=2023.2.0
  - mkl-include=2023.2.0
  - ninja
  - numpy>=2.1.0
  - python=3.13
  - pyyaml>=6.0.2
  - requests
  - six
  - typing_extensions
  - pip
  - pip:
    - opencv-contrib-python-headless==4.9.0.80
