name: base
#  moonvision/python-base
#
#  Dependencies include a small set of build-time
#  dependencies to ease compiling libraries.
channels:
  - conda-forge
dependencies:
  # switch all blas requirements to use mkl
  # implementation, see: https://conda-forge.org/docs/maintainer/knowledge_base.html#blas
  # it doesn't constrain the libblas version (1st *), but the build string to end in 'mkl' (2nd *)
  - libblas=*=*mkl
  - python=3.11
